# Makefile.in generated by automake 1.15.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2017 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/minicas
pkgincludedir = $(includedir)/minicas
pkglibdir = $(libdir)/minicas
pkglibexecdir = $(libexecdir)/minicas
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
check_PROGRAMS = t_basic$(EXEEXT) t_monomials$(EXEEXT) \
	t_monomial_pow$(EXEEXT) t_grades$(EXEEXT) \
	t_polynomials$(EXEEXT) t_polynomial_derive$(EXEEXT) \
	t_polynomial_eval$(EXEEXT) t_polynomial_div$(EXEEXT)
TESTS = script/basic/tst/basic_ops1.sh script/basic/tst/basic_ops2.sh \
	script/basic/tst/basic_ops3.sh script/basic/tst/basic_ops4.sh \
	script/basic/tst/basic_ops5.sh script/basic/tst/basic_ops6.sh \
	script/basic/tst/basic_ops7.sh script/basic/tst/basic_ops8.sh \
	script/basic/tst/basic_ops9.sh script/basic/tst/basic_ops10.sh \
	script/basic/tst/basic_ops11.sh \
	script/basic/tst/basic_ops12.sh \
	script/basic/tst/basic_ops13.sh t_monomials$(EXEEXT) \
	t_monomial_pow$(EXEEXT) t_grades$(EXEEXT) \
	t_polynomials$(EXEEXT) t_polynomial_derive$(EXEEXT) \
	t_polynomial_eval$(EXEEXT) t_polynomial_div$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(include_HEADERS) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libminicas_la_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_libminicas_la_OBJECTS = src/num_z/num_z.lo src/num_z/abs_bool.lo \
	src/num_z/attrib.lo src/num_z/base.lo src/num_z/bool.lo \
	src/num_z/io.lo src/num_z/num_ops.lo src/num_z/op_atrdiv.lo \
	src/num_z/op_atrmod.lo src/num_z/op_atrmul.lo \
	src/num_z/op_atrsub.lo src/num_z/op_atrsum.lo \
	src/num_z/opdiv.lo src/num_z/opmod.lo src/num_z/opmul.lo \
	src/num_z/opsub.lo src/num_z/opsum.lo src/num_z/private_ops.lo \
	src/num_z/unary_ops.lo src/num_zm/num_zm.lo \
	src/num_zm/attrib.lo src/num_zm/bool.lo src/num_zm/io.lo \
	src/num_zm/num_ops.lo src/num_zm/opdiv.lo src/num_zm/opmul.lo \
	src/num_zm/opsub.lo src/num_zm/opsum.lo src/num_q/num_q.lo \
	src/num_q/attrib.lo src/num_q/bool.lo src/num_q/io.lo \
	src/num_q/num_ops.lo src/num_q/op_atrdiv.lo \
	src/num_q/op_atrmul.lo src/num_q/op_atrsub.lo \
	src/num_q/op_atrsum.lo src/num_q/opdiv.lo src/num_q/opmul.lo \
	src/num_q/opsub.lo src/num_q/opsum.lo src/polynomial/attrib.lo \
	src/polynomial/bool.lo src/polynomial/coefficient_ops.lo \
	src/polynomial/degree_ops.lo \
	src/polynomial/content_and_primitive_part.lo \
	src/polynomial/io.lo src/polynomial/monomial_arithmetic_ops.lo \
	src/polynomial/monomial_bool_ops.lo \
	src/polynomial/monomial_general_ops.lo src/polynomial/opdiv.lo \
	src/polynomial/opmul.lo src/polynomial/opsub.lo \
	src/polynomial/opsum.lo src/polynomial/p_gcd.lo \
	src/polynomial/subs.lo src/polynomial/wrappers.lo \
	src/symbolic/Expr/Expr.lo src/symbolic/Expr/io.lo \
	src/symbolic/Expr/simplification.lo \
	src/symbolic/Expr/basic_simplification.lo \
	src/symbolic/Expr/operation_chains.lo \
	src/symbolic/Expr/merge_and_split.lo \
	src/symbolic/Expr/arithmetic_ops.lo src/symbolic/term/term.lo \
	src/symbolic/term/io.lo src/symbolic/term/cmp.lo \
	src/symbolic/functions/function.lo \
	src/symbolic/functions/io.lo src/symbolic/functions/cmp.lo \
	src/symbolic/functions/functors.lo
libminicas_la_OBJECTS = $(am_libminicas_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
am_t_basic_OBJECTS = script/basic/t_basic-t_basic.$(OBJEXT)
t_basic_OBJECTS = $(am_t_basic_OBJECTS)
t_basic_DEPENDENCIES = libminicas.la
am_t_grades_OBJECTS = script/polynomials/t_grades-t_grade.$(OBJEXT)
t_grades_OBJECTS = $(am_t_grades_OBJECTS)
t_grades_DEPENDENCIES = libminicas.la
am_t_monomial_pow_OBJECTS =  \
	script/polynomials/t_monomial_pow-t_monomial_pow.$(OBJEXT)
t_monomial_pow_OBJECTS = $(am_t_monomial_pow_OBJECTS)
t_monomial_pow_DEPENDENCIES = libminicas.la
am_t_monomials_OBJECTS =  \
	script/polynomials/t_monomials-t_monomials.$(OBJEXT)
t_monomials_OBJECTS = $(am_t_monomials_OBJECTS)
t_monomials_DEPENDENCIES = libminicas.la
am_t_polynomial_derive_OBJECTS = script/polynomials/t_polynomial_derive-t_polynomial_derivative.$(OBJEXT)
t_polynomial_derive_OBJECTS = $(am_t_polynomial_derive_OBJECTS)
t_polynomial_derive_DEPENDENCIES = libminicas.la
am_t_polynomial_div_OBJECTS = script/polynomials/t_polynomial_div-t_polynomial_div.$(OBJEXT)
t_polynomial_div_OBJECTS = $(am_t_polynomial_div_OBJECTS)
t_polynomial_div_DEPENDENCIES = libminicas.la
am_t_polynomial_eval_OBJECTS = script/polynomials/t_polynomial_eval-t_polynomial_eval.$(OBJEXT)
t_polynomial_eval_OBJECTS = $(am_t_polynomial_eval_OBJECTS)
t_polynomial_eval_DEPENDENCIES = libminicas.la
am_t_polynomials_OBJECTS =  \
	script/polynomials/t_polynomials-t_polynomials.$(OBJEXT)
t_polynomials_OBJECTS = $(am_t_polynomials_OBJECTS)
t_polynomials_DEPENDENCIES = libminicas.la
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(libminicas_la_SOURCES) $(t_basic_SOURCES) \
	$(t_grades_SOURCES) $(t_monomial_pow_SOURCES) \
	$(t_monomials_SOURCES) $(t_polynomial_derive_SOURCES) \
	$(t_polynomial_div_SOURCES) $(t_polynomial_eval_SOURCES) \
	$(t_polynomials_SOURCES)
DIST_SOURCES = $(libminicas_la_SOURCES) $(t_basic_SOURCES) \
	$(t_grades_SOURCES) $(t_monomial_pow_SOURCES) \
	$(t_monomials_SOURCES) $(t_polynomial_derive_SOURCES) \
	$(t_polynomial_div_SOURCES) $(t_polynomial_eval_SOURCES) \
	$(t_polynomials_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(include_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope check recheck
am__tty_colors_dummy = \
  mgn= red= grn= lgn= blu= brg= std=; \
  am__color_tests=no
am__tty_colors = { \
  $(am__tty_colors_dummy); \
  if test "X$(AM_COLOR_TESTS)" = Xno; then \
    am__color_tests=no; \
  elif test "X$(AM_COLOR_TESTS)" = Xalways; then \
    am__color_tests=yes; \
  elif test "X$$TERM" != Xdumb && { test -t 1; } 2>/dev/null; then \
    am__color_tests=yes; \
  fi; \
  if test $$am__color_tests = yes; then \
    red='[0;31m'; \
    grn='[0;32m'; \
    lgn='[1;32m'; \
    blu='[1;34m'; \
    mgn='[0;35m'; \
    brg='[1m'; \
    std='[m'; \
  fi; \
}
am__recheck_rx = ^[ 	]*:recheck:[ 	]*
am__global_test_result_rx = ^[ 	]*:global-test-result:[ 	]*
am__copy_in_global_log_rx = ^[ 	]*:copy-in-global-log:[ 	]*
# A command that, given a newline-separated list of test names on the
# standard input, print the name of the tests that are to be re-run
# upon "make recheck".
am__list_recheck_tests = $(AWK) '{ \
  recheck = 1; \
  while ((rc = (getline line < ($$0 ".trs"))) != 0) \
    { \
      if (rc < 0) \
        { \
          if ((getline line2 < ($$0 ".log")) < 0) \
	    recheck = 0; \
          break; \
        } \
      else if (line ~ /$(am__recheck_rx)[nN][Oo]/) \
        { \
          recheck = 0; \
          break; \
        } \
      else if (line ~ /$(am__recheck_rx)[yY][eE][sS]/) \
        { \
          break; \
        } \
    }; \
  if (recheck) \
    print $$0; \
  close ($$0 ".trs"); \
  close ($$0 ".log"); \
}'
# A command that, given a newline-separated list of test names on the
# standard input, create the global log from their .trs and .log files.
am__create_global_log = $(AWK) ' \
function fatal(msg) \
{ \
  print "fatal: making $@: " msg | "cat >&2"; \
  exit 1; \
} \
function rst_section(header) \
{ \
  print header; \
  len = length(header); \
  for (i = 1; i <= len; i = i + 1) \
    printf "="; \
  printf "\n\n"; \
} \
{ \
  copy_in_global_log = 1; \
  global_test_result = "RUN"; \
  while ((rc = (getline line < ($$0 ".trs"))) != 0) \
    { \
      if (rc < 0) \
         fatal("failed to read from " $$0 ".trs"); \
      if (line ~ /$(am__global_test_result_rx)/) \
        { \
          sub("$(am__global_test_result_rx)", "", line); \
          sub("[ 	]*$$", "", line); \
          global_test_result = line; \
        } \
      else if (line ~ /$(am__copy_in_global_log_rx)[nN][oO]/) \
        copy_in_global_log = 0; \
    }; \
  if (copy_in_global_log) \
    { \
      rst_section(global_test_result ": " $$0); \
      while ((rc = (getline line < ($$0 ".log"))) != 0) \
      { \
        if (rc < 0) \
          fatal("failed to read from " $$0 ".log"); \
        print line; \
      }; \
      printf "\n"; \
    }; \
  close ($$0 ".trs"); \
  close ($$0 ".log"); \
}'
# Restructured Text title.
am__rst_title = { sed 's/.*/   &   /;h;s/./=/g;p;x;s/ *$$//;p;g' && echo; }
# Solaris 10 'make', and several other traditional 'make' implementations,
# pass "-e" to $(SHELL), and POSIX 2008 even requires this.  Work around it
# by disabling -e (using the XSI extension "set +e") if it's set.
am__sh_e_setup = case $$- in *e*) set +e;; esac
# Default flags passed to test drivers.
am__common_driver_flags = \
  --color-tests "$$am__color_tests" \
  --enable-hard-errors "$$am__enable_hard_errors" \
  --expect-failure "$$am__expect_failure"
# To be inserted before the command running the test.  Creates the
# directory for the log if needed.  Stores in $dir the directory
# containing $f, in $tst the test, in $log the log.  Executes the
# developer- defined test setup AM_TESTS_ENVIRONMENT (if any), and
# passes TESTS_ENVIRONMENT.  Set up options for the wrapper that
# will run the test scripts (or their associated LOG_COMPILER, if
# thy have one).
am__check_pre = \
$(am__sh_e_setup);					\
$(am__vpath_adj_setup) $(am__vpath_adj)			\
$(am__tty_colors);					\
srcdir=$(srcdir); export srcdir;			\
case "$@" in						\
  */*) am__odir=`echo "./$@" | sed 's|/[^/]*$$||'`;;	\
    *) am__odir=.;; 					\
esac;							\
test "x$$am__odir" = x"." || test -d "$$am__odir" 	\
  || $(MKDIR_P) "$$am__odir" || exit $$?;		\
if test -f "./$$f"; then dir=./;			\
elif test -f "$$f"; then dir=;				\
else dir="$(srcdir)/"; fi;				\
tst=$$dir$$f; log='$@'; 				\
if test -n '$(DISABLE_HARD_ERRORS)'; then		\
  am__enable_hard_errors=no; 				\
else							\
  am__enable_hard_errors=yes; 				\
fi; 							\
case " $(XFAIL_TESTS) " in				\
  *[\ \	]$$f[\ \	]* | *[\ \	]$$dir$$f[\ \	]*) \
    am__expect_failure=yes;;				\
  *)							\
    am__expect_failure=no;;				\
esac; 							\
$(AM_TESTS_ENVIRONMENT) $(TESTS_ENVIRONMENT)
# A shell command to get the names of the tests scripts with any registered
# extension removed (i.e., equivalently, the names of the test logs, with
# the '.log' extension removed).  The result is saved in the shell variable
# '$bases'.  This honors runtime overriding of TESTS and TEST_LOGS.  Sadly,
# we cannot use something simpler, involving e.g., "$(TEST_LOGS:.log=)",
# since that might cause problem with VPATH rewrites for suffix-less tests.
# See also 'test-harness-vpath-rewrite.sh' and 'test-trs-basic.sh'.
am__set_TESTS_bases = \
  bases='$(TEST_LOGS)'; \
  bases=`for i in $$bases; do echo $$i; done | sed 's/\.log$$//'`; \
  bases=`echo $$bases`
RECHECK_LOGS = $(TEST_LOGS)
TEST_SUITE_LOG = test-suite.log
TEST_EXTENSIONS =  .test
LOG_DRIVER = $(SHELL) $(top_srcdir)/test-driver
LOG_COMPILE = $(LOG_COMPILER) $(AM_LOG_FLAGS) $(LOG_FLAGS)
am__set_b = \
  case '$@' in \
    */*) \
      case '$*' in \
        */*) b='$*';; \
          *) b=`echo '$@' | sed 's/\.log$$//'`; \
       esac;; \
    *) \
      b='$*';; \
  esac
am__test_logs1 = $(TESTS:=.log)
am__test_logs2 = $(am__test_logs1:.log=.log)
TEST_LOGS = $(am__test_logs2:.test.log=.log)
TEST_LOG_DRIVER = $(SHELL) $(top_srcdir)/test-driver
TEST_LOG_COMPILE = $(TEST_LOG_COMPILER) $(AM_TEST_LOG_FLAGS) \
	$(TEST_LOG_FLAGS)
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in compile \
	config.guess config.sub depcomp install-sh ltmain.sh missing \
	test-driver
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/arthur/Documents/mini-cas/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} /home/arthur/Documents/mini-cas/missing autoconf
AUTOHEADER = ${SHELL} /home/arthur/Documents/mini-cas/missing autoheader
AUTOMAKE = ${SHELL} /home/arthur/Documents/mini-cas/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -std=c++11 -O2 -Wall
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAKEINFO = ${SHELL} /home/arthur/Documents/mini-cas/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = minicas
PACKAGE_BUGREPORT = dealwithit@onyour.own
PACKAGE_NAME = minicas
PACKAGE_STRING = minicas beta
PACKAGE_TARNAME = minicas
PACKAGE_URL = 
PACKAGE_VERSION = beta
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = beta
abs_builddir = /home/arthur/Documents/mini-cas
abs_srcdir = /home/arthur/Documents/mini-cas
abs_top_builddir = /home/arthur/Documents/mini-cas
abs_top_srcdir = /home/arthur/Documents/mini-cas
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/arthur/Documents/mini-cas/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
ACLOCAL_AMFLAGS = -I m4
lib_LTLIBRARIES = libminicas.la
include_HEADERS = src/include/mini-cas \
		src/include/number.h \
		src/include/num_q.h \
		src/include/num_z.h \
		src/include/num_zm.h \
		src/include/monomial.h \
		src/include/monomial_comp_class.h \
		src/include/polynomial.h \
		src/include/term.h \
		src/include/function.h \
		src/include/Expr.h \
		src/include/template_ops.h \
		src/include/signatures.h

libminicas_la_SOURCES = src/num_z/num_z.cpp \
			src/num_z/abs_bool.cpp \
			src/num_z/attrib.cpp \
			src/num_z/base.cpp \
			src/num_z/bool.cpp \
			src/num_z/io.cpp \
			src/num_z/num_ops.cpp \
			src/num_z/op_atrdiv.cpp \
			src/num_z/op_atrmod.cpp \
			src/num_z/op_atrmul.cpp \
			src/num_z/op_atrsub.cpp \
			src/num_z/op_atrsum.cpp \
			src/num_z/opdiv.cpp \
			src/num_z/opmod.cpp \
			src/num_z/opmul.cpp \
			src/num_z/opsub.cpp \
			src/num_z/opsum.cpp \
			src/num_z/private_ops.cpp \
			src/num_z/unary_ops.cpp \
			src/num_zm/num_zm.cpp \
			src/num_zm/attrib.cpp \
			src/num_zm/bool.cpp \
			src/num_zm/io.cpp \
			src/num_zm/num_ops.cpp \
			src/num_zm/opdiv.cpp \
			src/num_zm/opmul.cpp \
			src/num_zm/opsub.cpp \
			src/num_zm/opsum.cpp \
			src/num_q/num_q.cpp \
			src/num_q/attrib.cpp \
			src/num_q/bool.cpp \
			src/num_q/io.cpp \
			src/num_q/num_ops.cpp \
			src/num_q/op_atrdiv.cpp \
			src/num_q/op_atrmul.cpp \
			src/num_q/op_atrsub.cpp \
			src/num_q/op_atrsum.cpp \
			src/num_q/opdiv.cpp \
			src/num_q/opmul.cpp \
			src/num_q/opsub.cpp \
			src/num_q/opsum.cpp \
			src/polynomial/attrib.cpp \
			src/polynomial/bool.cpp \
			src/polynomial/coefficient_ops.cpp \
			src/polynomial/degree_ops.cpp \
			src/polynomial/content_and_primitive_part.cpp \
			src/polynomial/io.cpp \
			src/polynomial/monomial_arithmetic_ops.cpp \
			src/polynomial/monomial_bool_ops.cpp \
			src/polynomial/monomial_general_ops.cpp \
			src/polynomial/opdiv.cpp \
			src/polynomial/opmul.cpp \
			src/polynomial/opsub.cpp \
			src/polynomial/opsum.cpp \
			src/polynomial/p_gcd.cpp \
			src/polynomial/subs.cpp \
			src/polynomial/wrappers.cpp \
			src/symbolic/Expr/Expr.cpp \
			src/symbolic/Expr/io.cpp \
			src/symbolic/Expr/simplification.cpp \
			src/symbolic/Expr/basic_simplification.cpp \
			src/symbolic/Expr/operation_chains.cpp \
			src/symbolic/Expr/merge_and_split.cpp \
			src/symbolic/Expr/arithmetic_ops.cpp \
			src/symbolic/term/term.cpp \
			src/symbolic/term/io.cpp \
			src/symbolic/term/cmp.cpp \
			src/symbolic/functions/function.cpp \
			src/symbolic/functions/io.cpp \
			src/symbolic/functions/cmp.cpp \
			src/symbolic/functions/functors.cpp

t_basic_CPPFLAGS = -I./src/include
t_basic_SOURCES = script/basic/t_basic.cpp
t_basic_LDADD = libminicas.la
t_monomials_CPPFLAGS = -I./src/include
t_monomials_SOURCES = script/polynomials/t_monomials.cpp
t_monomials_LDADD = libminicas.la
t_monomial_pow_CPPFLAGS = -I./src/include
t_monomial_pow_SOURCES = script/polynomials/t_monomial_pow.cpp
t_monomial_pow_LDADD = libminicas.la
t_grades_CPPFLAGS = -I./src/include
t_grades_SOURCES = script/polynomials/t_grade.cpp
t_grades_LDADD = libminicas.la
t_polynomials_CPPFLAGS = -I./src/include
t_polynomials_SOURCES = script/polynomials/t_polynomials.cpp
t_polynomials_LDADD = libminicas.la
t_polynomial_derive_CPPFLAGS = -I./src/include
t_polynomial_derive_SOURCES = script/polynomials/t_polynomial_derivative.cpp
t_polynomial_derive_LDADD = libminicas.la
t_polynomial_eval_CPPFLAGS = -I./src/include
t_polynomial_eval_SOURCES = script/polynomials/t_polynomial_eval.cpp
t_polynomial_eval_LDADD = libminicas.la
t_polynomial_div_CPPFLAGS = -I./src/include
t_polynomial_div_SOURCES = script/polynomials/t_polynomial_div.cpp
t_polynomial_div_LDADD = libminicas.la
EXTRA_DIST = $(TESTS) script/basic/in/inp1 script/basic/in/inp2 script/basic/in/inp3 script/basic/in/inp4 script/basic/in/inp5 script/basic/in/inp6 script/basic/in/inp7 script/basic/in/inp8 script/basic/in/inp9 script/basic/in/inp10 script/basic/in/inp11 script/basic/in/inp12 script/basic/in/inp13 script/basic/out/outg1 script/basic/out/outg2 script/basic/out/outg3 script/basic/out/outg4 script/basic/out/outg5 script/basic/out/outg6 script/basic/out/outg7 script/basic/out/outg8 script/basic/out/outg9 script/basic/out/outg10 script/basic/out/outg11 script/basic/out/outg12 script/basic/out/outg13 README.md LICENSE
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .lo .log .o .obj .test .test$(EXEEXT) .trs
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
src/num_z/$(am__dirstamp):
	@$(MKDIR_P) src/num_z
	@: > src/num_z/$(am__dirstamp)
src/num_z/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/num_z/$(DEPDIR)
	@: > src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/num_z.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/abs_bool.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/attrib.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/base.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/bool.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/io.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/num_ops.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/op_atrdiv.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/op_atrmod.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/op_atrmul.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/op_atrsub.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/op_atrsum.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/opdiv.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/opmod.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/opmul.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/opsub.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/opsum.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/private_ops.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_z/unary_ops.lo: src/num_z/$(am__dirstamp) \
	src/num_z/$(DEPDIR)/$(am__dirstamp)
src/num_zm/$(am__dirstamp):
	@$(MKDIR_P) src/num_zm
	@: > src/num_zm/$(am__dirstamp)
src/num_zm/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/num_zm/$(DEPDIR)
	@: > src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/num_zm.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/attrib.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/bool.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/io.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/num_ops.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/opdiv.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/opmul.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/opsub.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_zm/opsum.lo: src/num_zm/$(am__dirstamp) \
	src/num_zm/$(DEPDIR)/$(am__dirstamp)
src/num_q/$(am__dirstamp):
	@$(MKDIR_P) src/num_q
	@: > src/num_q/$(am__dirstamp)
src/num_q/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/num_q/$(DEPDIR)
	@: > src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/num_q.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/attrib.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/bool.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/io.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/num_ops.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/op_atrdiv.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/op_atrmul.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/op_atrsub.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/op_atrsum.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/opdiv.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/opmul.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/opsub.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/num_q/opsum.lo: src/num_q/$(am__dirstamp) \
	src/num_q/$(DEPDIR)/$(am__dirstamp)
src/polynomial/$(am__dirstamp):
	@$(MKDIR_P) src/polynomial
	@: > src/polynomial/$(am__dirstamp)
src/polynomial/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/polynomial/$(DEPDIR)
	@: > src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/attrib.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/bool.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/coefficient_ops.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/degree_ops.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/content_and_primitive_part.lo:  \
	src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/io.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/monomial_arithmetic_ops.lo:  \
	src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/monomial_bool_ops.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/monomial_general_ops.lo:  \
	src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/opdiv.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/opmul.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/opsub.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/opsum.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/p_gcd.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/subs.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/polynomial/wrappers.lo: src/polynomial/$(am__dirstamp) \
	src/polynomial/$(DEPDIR)/$(am__dirstamp)
src/symbolic/Expr/$(am__dirstamp):
	@$(MKDIR_P) src/symbolic/Expr
	@: > src/symbolic/Expr/$(am__dirstamp)
src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/symbolic/Expr/$(DEPDIR)
	@: > src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
src/symbolic/Expr/Expr.lo: src/symbolic/Expr/$(am__dirstamp) \
	src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
src/symbolic/Expr/io.lo: src/symbolic/Expr/$(am__dirstamp) \
	src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
src/symbolic/Expr/simplification.lo:  \
	src/symbolic/Expr/$(am__dirstamp) \
	src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
src/symbolic/Expr/basic_simplification.lo:  \
	src/symbolic/Expr/$(am__dirstamp) \
	src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
src/symbolic/Expr/operation_chains.lo:  \
	src/symbolic/Expr/$(am__dirstamp) \
	src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
src/symbolic/Expr/merge_and_split.lo:  \
	src/symbolic/Expr/$(am__dirstamp) \
	src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
src/symbolic/Expr/arithmetic_ops.lo:  \
	src/symbolic/Expr/$(am__dirstamp) \
	src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
src/symbolic/term/$(am__dirstamp):
	@$(MKDIR_P) src/symbolic/term
	@: > src/symbolic/term/$(am__dirstamp)
src/symbolic/term/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/symbolic/term/$(DEPDIR)
	@: > src/symbolic/term/$(DEPDIR)/$(am__dirstamp)
src/symbolic/term/term.lo: src/symbolic/term/$(am__dirstamp) \
	src/symbolic/term/$(DEPDIR)/$(am__dirstamp)
src/symbolic/term/io.lo: src/symbolic/term/$(am__dirstamp) \
	src/symbolic/term/$(DEPDIR)/$(am__dirstamp)
src/symbolic/term/cmp.lo: src/symbolic/term/$(am__dirstamp) \
	src/symbolic/term/$(DEPDIR)/$(am__dirstamp)
src/symbolic/functions/$(am__dirstamp):
	@$(MKDIR_P) src/symbolic/functions
	@: > src/symbolic/functions/$(am__dirstamp)
src/symbolic/functions/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/symbolic/functions/$(DEPDIR)
	@: > src/symbolic/functions/$(DEPDIR)/$(am__dirstamp)
src/symbolic/functions/function.lo:  \
	src/symbolic/functions/$(am__dirstamp) \
	src/symbolic/functions/$(DEPDIR)/$(am__dirstamp)
src/symbolic/functions/io.lo: src/symbolic/functions/$(am__dirstamp) \
	src/symbolic/functions/$(DEPDIR)/$(am__dirstamp)
src/symbolic/functions/cmp.lo: src/symbolic/functions/$(am__dirstamp) \
	src/symbolic/functions/$(DEPDIR)/$(am__dirstamp)
src/symbolic/functions/functors.lo:  \
	src/symbolic/functions/$(am__dirstamp) \
	src/symbolic/functions/$(DEPDIR)/$(am__dirstamp)

libminicas.la: $(libminicas_la_OBJECTS) $(libminicas_la_DEPENDENCIES) $(EXTRA_libminicas_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(CXXLINK) -rpath $(libdir) $(libminicas_la_OBJECTS) $(libminicas_la_LIBADD) $(LIBS)

clean-checkPROGRAMS:
	@list='$(check_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
script/basic/$(am__dirstamp):
	@$(MKDIR_P) script/basic
	@: > script/basic/$(am__dirstamp)
script/basic/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) script/basic/$(DEPDIR)
	@: > script/basic/$(DEPDIR)/$(am__dirstamp)
script/basic/t_basic-t_basic.$(OBJEXT): script/basic/$(am__dirstamp) \
	script/basic/$(DEPDIR)/$(am__dirstamp)

t_basic$(EXEEXT): $(t_basic_OBJECTS) $(t_basic_DEPENDENCIES) $(EXTRA_t_basic_DEPENDENCIES) 
	@rm -f t_basic$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(t_basic_OBJECTS) $(t_basic_LDADD) $(LIBS)
script/polynomials/$(am__dirstamp):
	@$(MKDIR_P) script/polynomials
	@: > script/polynomials/$(am__dirstamp)
script/polynomials/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) script/polynomials/$(DEPDIR)
	@: > script/polynomials/$(DEPDIR)/$(am__dirstamp)
script/polynomials/t_grades-t_grade.$(OBJEXT):  \
	script/polynomials/$(am__dirstamp) \
	script/polynomials/$(DEPDIR)/$(am__dirstamp)

t_grades$(EXEEXT): $(t_grades_OBJECTS) $(t_grades_DEPENDENCIES) $(EXTRA_t_grades_DEPENDENCIES) 
	@rm -f t_grades$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(t_grades_OBJECTS) $(t_grades_LDADD) $(LIBS)
script/polynomials/t_monomial_pow-t_monomial_pow.$(OBJEXT):  \
	script/polynomials/$(am__dirstamp) \
	script/polynomials/$(DEPDIR)/$(am__dirstamp)

t_monomial_pow$(EXEEXT): $(t_monomial_pow_OBJECTS) $(t_monomial_pow_DEPENDENCIES) $(EXTRA_t_monomial_pow_DEPENDENCIES) 
	@rm -f t_monomial_pow$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(t_monomial_pow_OBJECTS) $(t_monomial_pow_LDADD) $(LIBS)
script/polynomials/t_monomials-t_monomials.$(OBJEXT):  \
	script/polynomials/$(am__dirstamp) \
	script/polynomials/$(DEPDIR)/$(am__dirstamp)

t_monomials$(EXEEXT): $(t_monomials_OBJECTS) $(t_monomials_DEPENDENCIES) $(EXTRA_t_monomials_DEPENDENCIES) 
	@rm -f t_monomials$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(t_monomials_OBJECTS) $(t_monomials_LDADD) $(LIBS)
script/polynomials/t_polynomial_derive-t_polynomial_derivative.$(OBJEXT):  \
	script/polynomials/$(am__dirstamp) \
	script/polynomials/$(DEPDIR)/$(am__dirstamp)

t_polynomial_derive$(EXEEXT): $(t_polynomial_derive_OBJECTS) $(t_polynomial_derive_DEPENDENCIES) $(EXTRA_t_polynomial_derive_DEPENDENCIES) 
	@rm -f t_polynomial_derive$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(t_polynomial_derive_OBJECTS) $(t_polynomial_derive_LDADD) $(LIBS)
script/polynomials/t_polynomial_div-t_polynomial_div.$(OBJEXT):  \
	script/polynomials/$(am__dirstamp) \
	script/polynomials/$(DEPDIR)/$(am__dirstamp)

t_polynomial_div$(EXEEXT): $(t_polynomial_div_OBJECTS) $(t_polynomial_div_DEPENDENCIES) $(EXTRA_t_polynomial_div_DEPENDENCIES) 
	@rm -f t_polynomial_div$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(t_polynomial_div_OBJECTS) $(t_polynomial_div_LDADD) $(LIBS)
script/polynomials/t_polynomial_eval-t_polynomial_eval.$(OBJEXT):  \
	script/polynomials/$(am__dirstamp) \
	script/polynomials/$(DEPDIR)/$(am__dirstamp)

t_polynomial_eval$(EXEEXT): $(t_polynomial_eval_OBJECTS) $(t_polynomial_eval_DEPENDENCIES) $(EXTRA_t_polynomial_eval_DEPENDENCIES) 
	@rm -f t_polynomial_eval$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(t_polynomial_eval_OBJECTS) $(t_polynomial_eval_LDADD) $(LIBS)
script/polynomials/t_polynomials-t_polynomials.$(OBJEXT):  \
	script/polynomials/$(am__dirstamp) \
	script/polynomials/$(DEPDIR)/$(am__dirstamp)

t_polynomials$(EXEEXT): $(t_polynomials_OBJECTS) $(t_polynomials_DEPENDENCIES) $(EXTRA_t_polynomials_DEPENDENCIES) 
	@rm -f t_polynomials$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(t_polynomials_OBJECTS) $(t_polynomials_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f script/basic/*.$(OBJEXT)
	-rm -f script/polynomials/*.$(OBJEXT)
	-rm -f src/num_q/*.$(OBJEXT)
	-rm -f src/num_q/*.lo
	-rm -f src/num_z/*.$(OBJEXT)
	-rm -f src/num_z/*.lo
	-rm -f src/num_zm/*.$(OBJEXT)
	-rm -f src/num_zm/*.lo
	-rm -f src/polynomial/*.$(OBJEXT)
	-rm -f src/polynomial/*.lo
	-rm -f src/symbolic/Expr/*.$(OBJEXT)
	-rm -f src/symbolic/Expr/*.lo
	-rm -f src/symbolic/functions/*.$(OBJEXT)
	-rm -f src/symbolic/functions/*.lo
	-rm -f src/symbolic/term/*.$(OBJEXT)
	-rm -f src/symbolic/term/*.lo

distclean-compile:
	-rm -f *.tab.c

include script/basic/$(DEPDIR)/t_basic-t_basic.Po
include script/polynomials/$(DEPDIR)/t_grades-t_grade.Po
include script/polynomials/$(DEPDIR)/t_monomial_pow-t_monomial_pow.Po
include script/polynomials/$(DEPDIR)/t_monomials-t_monomials.Po
include script/polynomials/$(DEPDIR)/t_polynomial_derive-t_polynomial_derivative.Po
include script/polynomials/$(DEPDIR)/t_polynomial_div-t_polynomial_div.Po
include script/polynomials/$(DEPDIR)/t_polynomial_eval-t_polynomial_eval.Po
include script/polynomials/$(DEPDIR)/t_polynomials-t_polynomials.Po
include src/num_q/$(DEPDIR)/attrib.Plo
include src/num_q/$(DEPDIR)/bool.Plo
include src/num_q/$(DEPDIR)/io.Plo
include src/num_q/$(DEPDIR)/num_ops.Plo
include src/num_q/$(DEPDIR)/num_q.Plo
include src/num_q/$(DEPDIR)/op_atrdiv.Plo
include src/num_q/$(DEPDIR)/op_atrmul.Plo
include src/num_q/$(DEPDIR)/op_atrsub.Plo
include src/num_q/$(DEPDIR)/op_atrsum.Plo
include src/num_q/$(DEPDIR)/opdiv.Plo
include src/num_q/$(DEPDIR)/opmul.Plo
include src/num_q/$(DEPDIR)/opsub.Plo
include src/num_q/$(DEPDIR)/opsum.Plo
include src/num_z/$(DEPDIR)/abs_bool.Plo
include src/num_z/$(DEPDIR)/attrib.Plo
include src/num_z/$(DEPDIR)/base.Plo
include src/num_z/$(DEPDIR)/bool.Plo
include src/num_z/$(DEPDIR)/io.Plo
include src/num_z/$(DEPDIR)/num_ops.Plo
include src/num_z/$(DEPDIR)/num_z.Plo
include src/num_z/$(DEPDIR)/op_atrdiv.Plo
include src/num_z/$(DEPDIR)/op_atrmod.Plo
include src/num_z/$(DEPDIR)/op_atrmul.Plo
include src/num_z/$(DEPDIR)/op_atrsub.Plo
include src/num_z/$(DEPDIR)/op_atrsum.Plo
include src/num_z/$(DEPDIR)/opdiv.Plo
include src/num_z/$(DEPDIR)/opmod.Plo
include src/num_z/$(DEPDIR)/opmul.Plo
include src/num_z/$(DEPDIR)/opsub.Plo
include src/num_z/$(DEPDIR)/opsum.Plo
include src/num_z/$(DEPDIR)/private_ops.Plo
include src/num_z/$(DEPDIR)/unary_ops.Plo
include src/num_zm/$(DEPDIR)/attrib.Plo
include src/num_zm/$(DEPDIR)/bool.Plo
include src/num_zm/$(DEPDIR)/io.Plo
include src/num_zm/$(DEPDIR)/num_ops.Plo
include src/num_zm/$(DEPDIR)/num_zm.Plo
include src/num_zm/$(DEPDIR)/opdiv.Plo
include src/num_zm/$(DEPDIR)/opmul.Plo
include src/num_zm/$(DEPDIR)/opsub.Plo
include src/num_zm/$(DEPDIR)/opsum.Plo
include src/polynomial/$(DEPDIR)/attrib.Plo
include src/polynomial/$(DEPDIR)/bool.Plo
include src/polynomial/$(DEPDIR)/coefficient_ops.Plo
include src/polynomial/$(DEPDIR)/content_and_primitive_part.Plo
include src/polynomial/$(DEPDIR)/degree_ops.Plo
include src/polynomial/$(DEPDIR)/io.Plo
include src/polynomial/$(DEPDIR)/monomial_arithmetic_ops.Plo
include src/polynomial/$(DEPDIR)/monomial_bool_ops.Plo
include src/polynomial/$(DEPDIR)/monomial_general_ops.Plo
include src/polynomial/$(DEPDIR)/opdiv.Plo
include src/polynomial/$(DEPDIR)/opmul.Plo
include src/polynomial/$(DEPDIR)/opsub.Plo
include src/polynomial/$(DEPDIR)/opsum.Plo
include src/polynomial/$(DEPDIR)/p_gcd.Plo
include src/polynomial/$(DEPDIR)/subs.Plo
include src/polynomial/$(DEPDIR)/wrappers.Plo
include src/symbolic/Expr/$(DEPDIR)/Expr.Plo
include src/symbolic/Expr/$(DEPDIR)/arithmetic_ops.Plo
include src/symbolic/Expr/$(DEPDIR)/basic_simplification.Plo
include src/symbolic/Expr/$(DEPDIR)/io.Plo
include src/symbolic/Expr/$(DEPDIR)/merge_and_split.Plo
include src/symbolic/Expr/$(DEPDIR)/operation_chains.Plo
include src/symbolic/Expr/$(DEPDIR)/simplification.Plo
include src/symbolic/functions/$(DEPDIR)/cmp.Plo
include src/symbolic/functions/$(DEPDIR)/function.Plo
include src/symbolic/functions/$(DEPDIR)/functors.Plo
include src/symbolic/functions/$(DEPDIR)/io.Plo
include src/symbolic/term/$(DEPDIR)/cmp.Plo
include src/symbolic/term/$(DEPDIR)/io.Plo
include src/symbolic/term/$(DEPDIR)/term.Plo

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

script/basic/t_basic-t_basic.o: script/basic/t_basic.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_basic_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/basic/t_basic-t_basic.o -MD -MP -MF script/basic/$(DEPDIR)/t_basic-t_basic.Tpo -c -o script/basic/t_basic-t_basic.o `test -f 'script/basic/t_basic.cpp' || echo '$(srcdir)/'`script/basic/t_basic.cpp
	$(AM_V_at)$(am__mv) script/basic/$(DEPDIR)/t_basic-t_basic.Tpo script/basic/$(DEPDIR)/t_basic-t_basic.Po
#	$(AM_V_CXX)source='script/basic/t_basic.cpp' object='script/basic/t_basic-t_basic.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_basic_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/basic/t_basic-t_basic.o `test -f 'script/basic/t_basic.cpp' || echo '$(srcdir)/'`script/basic/t_basic.cpp

script/basic/t_basic-t_basic.obj: script/basic/t_basic.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_basic_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/basic/t_basic-t_basic.obj -MD -MP -MF script/basic/$(DEPDIR)/t_basic-t_basic.Tpo -c -o script/basic/t_basic-t_basic.obj `if test -f 'script/basic/t_basic.cpp'; then $(CYGPATH_W) 'script/basic/t_basic.cpp'; else $(CYGPATH_W) '$(srcdir)/script/basic/t_basic.cpp'; fi`
	$(AM_V_at)$(am__mv) script/basic/$(DEPDIR)/t_basic-t_basic.Tpo script/basic/$(DEPDIR)/t_basic-t_basic.Po
#	$(AM_V_CXX)source='script/basic/t_basic.cpp' object='script/basic/t_basic-t_basic.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_basic_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/basic/t_basic-t_basic.obj `if test -f 'script/basic/t_basic.cpp'; then $(CYGPATH_W) 'script/basic/t_basic.cpp'; else $(CYGPATH_W) '$(srcdir)/script/basic/t_basic.cpp'; fi`

script/polynomials/t_grades-t_grade.o: script/polynomials/t_grade.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_grades_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_grades-t_grade.o -MD -MP -MF script/polynomials/$(DEPDIR)/t_grades-t_grade.Tpo -c -o script/polynomials/t_grades-t_grade.o `test -f 'script/polynomials/t_grade.cpp' || echo '$(srcdir)/'`script/polynomials/t_grade.cpp
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_grades-t_grade.Tpo script/polynomials/$(DEPDIR)/t_grades-t_grade.Po
#	$(AM_V_CXX)source='script/polynomials/t_grade.cpp' object='script/polynomials/t_grades-t_grade.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_grades_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_grades-t_grade.o `test -f 'script/polynomials/t_grade.cpp' || echo '$(srcdir)/'`script/polynomials/t_grade.cpp

script/polynomials/t_grades-t_grade.obj: script/polynomials/t_grade.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_grades_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_grades-t_grade.obj -MD -MP -MF script/polynomials/$(DEPDIR)/t_grades-t_grade.Tpo -c -o script/polynomials/t_grades-t_grade.obj `if test -f 'script/polynomials/t_grade.cpp'; then $(CYGPATH_W) 'script/polynomials/t_grade.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_grade.cpp'; fi`
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_grades-t_grade.Tpo script/polynomials/$(DEPDIR)/t_grades-t_grade.Po
#	$(AM_V_CXX)source='script/polynomials/t_grade.cpp' object='script/polynomials/t_grades-t_grade.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_grades_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_grades-t_grade.obj `if test -f 'script/polynomials/t_grade.cpp'; then $(CYGPATH_W) 'script/polynomials/t_grade.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_grade.cpp'; fi`

script/polynomials/t_monomial_pow-t_monomial_pow.o: script/polynomials/t_monomial_pow.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_monomial_pow_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_monomial_pow-t_monomial_pow.o -MD -MP -MF script/polynomials/$(DEPDIR)/t_monomial_pow-t_monomial_pow.Tpo -c -o script/polynomials/t_monomial_pow-t_monomial_pow.o `test -f 'script/polynomials/t_monomial_pow.cpp' || echo '$(srcdir)/'`script/polynomials/t_monomial_pow.cpp
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_monomial_pow-t_monomial_pow.Tpo script/polynomials/$(DEPDIR)/t_monomial_pow-t_monomial_pow.Po
#	$(AM_V_CXX)source='script/polynomials/t_monomial_pow.cpp' object='script/polynomials/t_monomial_pow-t_monomial_pow.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_monomial_pow_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_monomial_pow-t_monomial_pow.o `test -f 'script/polynomials/t_monomial_pow.cpp' || echo '$(srcdir)/'`script/polynomials/t_monomial_pow.cpp

script/polynomials/t_monomial_pow-t_monomial_pow.obj: script/polynomials/t_monomial_pow.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_monomial_pow_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_monomial_pow-t_monomial_pow.obj -MD -MP -MF script/polynomials/$(DEPDIR)/t_monomial_pow-t_monomial_pow.Tpo -c -o script/polynomials/t_monomial_pow-t_monomial_pow.obj `if test -f 'script/polynomials/t_monomial_pow.cpp'; then $(CYGPATH_W) 'script/polynomials/t_monomial_pow.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_monomial_pow.cpp'; fi`
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_monomial_pow-t_monomial_pow.Tpo script/polynomials/$(DEPDIR)/t_monomial_pow-t_monomial_pow.Po
#	$(AM_V_CXX)source='script/polynomials/t_monomial_pow.cpp' object='script/polynomials/t_monomial_pow-t_monomial_pow.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_monomial_pow_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_monomial_pow-t_monomial_pow.obj `if test -f 'script/polynomials/t_monomial_pow.cpp'; then $(CYGPATH_W) 'script/polynomials/t_monomial_pow.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_monomial_pow.cpp'; fi`

script/polynomials/t_monomials-t_monomials.o: script/polynomials/t_monomials.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_monomials_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_monomials-t_monomials.o -MD -MP -MF script/polynomials/$(DEPDIR)/t_monomials-t_monomials.Tpo -c -o script/polynomials/t_monomials-t_monomials.o `test -f 'script/polynomials/t_monomials.cpp' || echo '$(srcdir)/'`script/polynomials/t_monomials.cpp
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_monomials-t_monomials.Tpo script/polynomials/$(DEPDIR)/t_monomials-t_monomials.Po
#	$(AM_V_CXX)source='script/polynomials/t_monomials.cpp' object='script/polynomials/t_monomials-t_monomials.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_monomials_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_monomials-t_monomials.o `test -f 'script/polynomials/t_monomials.cpp' || echo '$(srcdir)/'`script/polynomials/t_monomials.cpp

script/polynomials/t_monomials-t_monomials.obj: script/polynomials/t_monomials.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_monomials_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_monomials-t_monomials.obj -MD -MP -MF script/polynomials/$(DEPDIR)/t_monomials-t_monomials.Tpo -c -o script/polynomials/t_monomials-t_monomials.obj `if test -f 'script/polynomials/t_monomials.cpp'; then $(CYGPATH_W) 'script/polynomials/t_monomials.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_monomials.cpp'; fi`
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_monomials-t_monomials.Tpo script/polynomials/$(DEPDIR)/t_monomials-t_monomials.Po
#	$(AM_V_CXX)source='script/polynomials/t_monomials.cpp' object='script/polynomials/t_monomials-t_monomials.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_monomials_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_monomials-t_monomials.obj `if test -f 'script/polynomials/t_monomials.cpp'; then $(CYGPATH_W) 'script/polynomials/t_monomials.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_monomials.cpp'; fi`

script/polynomials/t_polynomial_derive-t_polynomial_derivative.o: script/polynomials/t_polynomial_derivative.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_derive_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_polynomial_derive-t_polynomial_derivative.o -MD -MP -MF script/polynomials/$(DEPDIR)/t_polynomial_derive-t_polynomial_derivative.Tpo -c -o script/polynomials/t_polynomial_derive-t_polynomial_derivative.o `test -f 'script/polynomials/t_polynomial_derivative.cpp' || echo '$(srcdir)/'`script/polynomials/t_polynomial_derivative.cpp
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_polynomial_derive-t_polynomial_derivative.Tpo script/polynomials/$(DEPDIR)/t_polynomial_derive-t_polynomial_derivative.Po
#	$(AM_V_CXX)source='script/polynomials/t_polynomial_derivative.cpp' object='script/polynomials/t_polynomial_derive-t_polynomial_derivative.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_derive_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_polynomial_derive-t_polynomial_derivative.o `test -f 'script/polynomials/t_polynomial_derivative.cpp' || echo '$(srcdir)/'`script/polynomials/t_polynomial_derivative.cpp

script/polynomials/t_polynomial_derive-t_polynomial_derivative.obj: script/polynomials/t_polynomial_derivative.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_derive_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_polynomial_derive-t_polynomial_derivative.obj -MD -MP -MF script/polynomials/$(DEPDIR)/t_polynomial_derive-t_polynomial_derivative.Tpo -c -o script/polynomials/t_polynomial_derive-t_polynomial_derivative.obj `if test -f 'script/polynomials/t_polynomial_derivative.cpp'; then $(CYGPATH_W) 'script/polynomials/t_polynomial_derivative.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_polynomial_derivative.cpp'; fi`
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_polynomial_derive-t_polynomial_derivative.Tpo script/polynomials/$(DEPDIR)/t_polynomial_derive-t_polynomial_derivative.Po
#	$(AM_V_CXX)source='script/polynomials/t_polynomial_derivative.cpp' object='script/polynomials/t_polynomial_derive-t_polynomial_derivative.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_derive_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_polynomial_derive-t_polynomial_derivative.obj `if test -f 'script/polynomials/t_polynomial_derivative.cpp'; then $(CYGPATH_W) 'script/polynomials/t_polynomial_derivative.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_polynomial_derivative.cpp'; fi`

script/polynomials/t_polynomial_div-t_polynomial_div.o: script/polynomials/t_polynomial_div.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_div_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_polynomial_div-t_polynomial_div.o -MD -MP -MF script/polynomials/$(DEPDIR)/t_polynomial_div-t_polynomial_div.Tpo -c -o script/polynomials/t_polynomial_div-t_polynomial_div.o `test -f 'script/polynomials/t_polynomial_div.cpp' || echo '$(srcdir)/'`script/polynomials/t_polynomial_div.cpp
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_polynomial_div-t_polynomial_div.Tpo script/polynomials/$(DEPDIR)/t_polynomial_div-t_polynomial_div.Po
#	$(AM_V_CXX)source='script/polynomials/t_polynomial_div.cpp' object='script/polynomials/t_polynomial_div-t_polynomial_div.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_div_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_polynomial_div-t_polynomial_div.o `test -f 'script/polynomials/t_polynomial_div.cpp' || echo '$(srcdir)/'`script/polynomials/t_polynomial_div.cpp

script/polynomials/t_polynomial_div-t_polynomial_div.obj: script/polynomials/t_polynomial_div.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_div_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_polynomial_div-t_polynomial_div.obj -MD -MP -MF script/polynomials/$(DEPDIR)/t_polynomial_div-t_polynomial_div.Tpo -c -o script/polynomials/t_polynomial_div-t_polynomial_div.obj `if test -f 'script/polynomials/t_polynomial_div.cpp'; then $(CYGPATH_W) 'script/polynomials/t_polynomial_div.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_polynomial_div.cpp'; fi`
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_polynomial_div-t_polynomial_div.Tpo script/polynomials/$(DEPDIR)/t_polynomial_div-t_polynomial_div.Po
#	$(AM_V_CXX)source='script/polynomials/t_polynomial_div.cpp' object='script/polynomials/t_polynomial_div-t_polynomial_div.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_div_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_polynomial_div-t_polynomial_div.obj `if test -f 'script/polynomials/t_polynomial_div.cpp'; then $(CYGPATH_W) 'script/polynomials/t_polynomial_div.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_polynomial_div.cpp'; fi`

script/polynomials/t_polynomial_eval-t_polynomial_eval.o: script/polynomials/t_polynomial_eval.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_eval_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_polynomial_eval-t_polynomial_eval.o -MD -MP -MF script/polynomials/$(DEPDIR)/t_polynomial_eval-t_polynomial_eval.Tpo -c -o script/polynomials/t_polynomial_eval-t_polynomial_eval.o `test -f 'script/polynomials/t_polynomial_eval.cpp' || echo '$(srcdir)/'`script/polynomials/t_polynomial_eval.cpp
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_polynomial_eval-t_polynomial_eval.Tpo script/polynomials/$(DEPDIR)/t_polynomial_eval-t_polynomial_eval.Po
#	$(AM_V_CXX)source='script/polynomials/t_polynomial_eval.cpp' object='script/polynomials/t_polynomial_eval-t_polynomial_eval.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_eval_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_polynomial_eval-t_polynomial_eval.o `test -f 'script/polynomials/t_polynomial_eval.cpp' || echo '$(srcdir)/'`script/polynomials/t_polynomial_eval.cpp

script/polynomials/t_polynomial_eval-t_polynomial_eval.obj: script/polynomials/t_polynomial_eval.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_eval_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_polynomial_eval-t_polynomial_eval.obj -MD -MP -MF script/polynomials/$(DEPDIR)/t_polynomial_eval-t_polynomial_eval.Tpo -c -o script/polynomials/t_polynomial_eval-t_polynomial_eval.obj `if test -f 'script/polynomials/t_polynomial_eval.cpp'; then $(CYGPATH_W) 'script/polynomials/t_polynomial_eval.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_polynomial_eval.cpp'; fi`
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_polynomial_eval-t_polynomial_eval.Tpo script/polynomials/$(DEPDIR)/t_polynomial_eval-t_polynomial_eval.Po
#	$(AM_V_CXX)source='script/polynomials/t_polynomial_eval.cpp' object='script/polynomials/t_polynomial_eval-t_polynomial_eval.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomial_eval_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_polynomial_eval-t_polynomial_eval.obj `if test -f 'script/polynomials/t_polynomial_eval.cpp'; then $(CYGPATH_W) 'script/polynomials/t_polynomial_eval.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_polynomial_eval.cpp'; fi`

script/polynomials/t_polynomials-t_polynomials.o: script/polynomials/t_polynomials.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomials_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_polynomials-t_polynomials.o -MD -MP -MF script/polynomials/$(DEPDIR)/t_polynomials-t_polynomials.Tpo -c -o script/polynomials/t_polynomials-t_polynomials.o `test -f 'script/polynomials/t_polynomials.cpp' || echo '$(srcdir)/'`script/polynomials/t_polynomials.cpp
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_polynomials-t_polynomials.Tpo script/polynomials/$(DEPDIR)/t_polynomials-t_polynomials.Po
#	$(AM_V_CXX)source='script/polynomials/t_polynomials.cpp' object='script/polynomials/t_polynomials-t_polynomials.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomials_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_polynomials-t_polynomials.o `test -f 'script/polynomials/t_polynomials.cpp' || echo '$(srcdir)/'`script/polynomials/t_polynomials.cpp

script/polynomials/t_polynomials-t_polynomials.obj: script/polynomials/t_polynomials.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomials_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT script/polynomials/t_polynomials-t_polynomials.obj -MD -MP -MF script/polynomials/$(DEPDIR)/t_polynomials-t_polynomials.Tpo -c -o script/polynomials/t_polynomials-t_polynomials.obj `if test -f 'script/polynomials/t_polynomials.cpp'; then $(CYGPATH_W) 'script/polynomials/t_polynomials.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_polynomials.cpp'; fi`
	$(AM_V_at)$(am__mv) script/polynomials/$(DEPDIR)/t_polynomials-t_polynomials.Tpo script/polynomials/$(DEPDIR)/t_polynomials-t_polynomials.Po
#	$(AM_V_CXX)source='script/polynomials/t_polynomials.cpp' object='script/polynomials/t_polynomials-t_polynomials.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(t_polynomials_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o script/polynomials/t_polynomials-t_polynomials.obj `if test -f 'script/polynomials/t_polynomials.cpp'; then $(CYGPATH_W) 'script/polynomials/t_polynomials.cpp'; else $(CYGPATH_W) '$(srcdir)/script/polynomials/t_polynomials.cpp'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf src/num_q/.libs src/num_q/_libs
	-rm -rf src/num_z/.libs src/num_z/_libs
	-rm -rf src/num_zm/.libs src/num_zm/_libs
	-rm -rf src/polynomial/.libs src/polynomial/_libs
	-rm -rf src/symbolic/Expr/.libs src/symbolic/Expr/_libs
	-rm -rf src/symbolic/functions/.libs src/symbolic/functions/_libs
	-rm -rf src/symbolic/term/.libs src/symbolic/term/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-includeHEADERS: $(include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(includedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(includedir)" || exit $$?; \
	done

uninstall-includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(include_HEADERS)'; test -n "$(includedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

# Recover from deleted '.trs' file; this should ensure that
# "rm -f foo.log; make foo.trs" re-run 'foo.test', and re-create
# both 'foo.log' and 'foo.trs'.  Break the recipe in two subshells
# to avoid problems with "make -n".
.log.trs:
	rm -f $< $@
	$(MAKE) $(AM_MAKEFLAGS) $<

# Leading 'am--fnord' is there to ensure the list of targets does not
# expand to empty, as could happen e.g. with make check TESTS=''.
am--fnord $(TEST_LOGS) $(TEST_LOGS:.log=.trs): $(am__force_recheck)
am--force-recheck:
	@:

$(TEST_SUITE_LOG): $(TEST_LOGS)
	@$(am__set_TESTS_bases); \
	am__f_ok () { test -f "$$1" && test -r "$$1"; }; \
	redo_bases=`for i in $$bases; do \
	              am__f_ok $$i.trs && am__f_ok $$i.log || echo $$i; \
	            done`; \
	if test -n "$$redo_bases"; then \
	  redo_logs=`for i in $$redo_bases; do echo $$i.log; done`; \
	  redo_results=`for i in $$redo_bases; do echo $$i.trs; done`; \
	  if $(am__make_dryrun); then :; else \
	    rm -f $$redo_logs && rm -f $$redo_results || exit 1; \
	  fi; \
	fi; \
	if test -n "$$am__remaking_logs"; then \
	  echo "fatal: making $(TEST_SUITE_LOG): possible infinite" \
	       "recursion detected" >&2; \
	elif test -n "$$redo_logs"; then \
	  am__remaking_logs=yes $(MAKE) $(AM_MAKEFLAGS) $$redo_logs; \
	fi; \
	if $(am__make_dryrun); then :; else \
	  st=0;  \
	  errmsg="fatal: making $(TEST_SUITE_LOG): failed to create"; \
	  for i in $$redo_bases; do \
	    test -f $$i.trs && test -r $$i.trs \
	      || { echo "$$errmsg $$i.trs" >&2; st=1; }; \
	    test -f $$i.log && test -r $$i.log \
	      || { echo "$$errmsg $$i.log" >&2; st=1; }; \
	  done; \
	  test $$st -eq 0 || exit 1; \
	fi
	@$(am__sh_e_setup); $(am__tty_colors); $(am__set_TESTS_bases); \
	ws='[ 	]'; \
	results=`for b in $$bases; do echo $$b.trs; done`; \
	test -n "$$results" || results=/dev/null; \
	all=`  grep "^$$ws*:test-result:"           $$results | wc -l`; \
	pass=` grep "^$$ws*:test-result:$$ws*PASS"  $$results | wc -l`; \
	fail=` grep "^$$ws*:test-result:$$ws*FAIL"  $$results | wc -l`; \
	skip=` grep "^$$ws*:test-result:$$ws*SKIP"  $$results | wc -l`; \
	xfail=`grep "^$$ws*:test-result:$$ws*XFAIL" $$results | wc -l`; \
	xpass=`grep "^$$ws*:test-result:$$ws*XPASS" $$results | wc -l`; \
	error=`grep "^$$ws*:test-result:$$ws*ERROR" $$results | wc -l`; \
	if test `expr $$fail + $$xpass + $$error` -eq 0; then \
	  success=true; \
	else \
	  success=false; \
	fi; \
	br='==================='; br=$$br$$br$$br$$br; \
	result_count () \
	{ \
	    if test x"$$1" = x"--maybe-color"; then \
	      maybe_colorize=yes; \
	    elif test x"$$1" = x"--no-color"; then \
	      maybe_colorize=no; \
	    else \
	      echo "$@: invalid 'result_count' usage" >&2; exit 4; \
	    fi; \
	    shift; \
	    desc=$$1 count=$$2; \
	    if test $$maybe_colorize = yes && test $$count -gt 0; then \
	      color_start=$$3 color_end=$$std; \
	    else \
	      color_start= color_end=; \
	    fi; \
	    echo "$${color_start}# $$desc $$count$${color_end}"; \
	}; \
	create_testsuite_report () \
	{ \
	  result_count $$1 "TOTAL:" $$all   "$$brg"; \
	  result_count $$1 "PASS: " $$pass  "$$grn"; \
	  result_count $$1 "SKIP: " $$skip  "$$blu"; \
	  result_count $$1 "XFAIL:" $$xfail "$$lgn"; \
	  result_count $$1 "FAIL: " $$fail  "$$red"; \
	  result_count $$1 "XPASS:" $$xpass "$$red"; \
	  result_count $$1 "ERROR:" $$error "$$mgn"; \
	}; \
	{								\
	  echo "$(PACKAGE_STRING): $(subdir)/$(TEST_SUITE_LOG)" |	\
	    $(am__rst_title);						\
	  create_testsuite_report --no-color;				\
	  echo;								\
	  echo ".. contents:: :depth: 2";				\
	  echo;								\
	  for b in $$bases; do echo $$b; done				\
	    | $(am__create_global_log);					\
	} >$(TEST_SUITE_LOG).tmp || exit 1;				\
	mv $(TEST_SUITE_LOG).tmp $(TEST_SUITE_LOG);			\
	if $$success; then						\
	  col="$$grn";							\
	 else								\
	  col="$$red";							\
	  test x"$$VERBOSE" = x || cat $(TEST_SUITE_LOG);		\
	fi;								\
	echo "$${col}$$br$${std}"; 					\
	echo "$${col}Testsuite summary for $(PACKAGE_STRING)$${std}";	\
	echo "$${col}$$br$${std}"; 					\
	create_testsuite_report --maybe-color;				\
	echo "$$col$$br$$std";						\
	if $$success; then :; else					\
	  echo "$${col}See $(subdir)/$(TEST_SUITE_LOG)$${std}";		\
	  if test -n "$(PACKAGE_BUGREPORT)"; then			\
	    echo "$${col}Please report to $(PACKAGE_BUGREPORT)$${std}";	\
	  fi;								\
	  echo "$$col$$br$$std";					\
	fi;								\
	$$success || exit 1

check-TESTS:
	@list='$(RECHECK_LOGS)';           test -z "$$list" || rm -f $$list
	@list='$(RECHECK_LOGS:.log=.trs)'; test -z "$$list" || rm -f $$list
	@test -z "$(TEST_SUITE_LOG)" || rm -f $(TEST_SUITE_LOG)
	@set +e; $(am__set_TESTS_bases); \
	log_list=`for i in $$bases; do echo $$i.log; done`; \
	trs_list=`for i in $$bases; do echo $$i.trs; done`; \
	log_list=`echo $$log_list`; trs_list=`echo $$trs_list`; \
	$(MAKE) $(AM_MAKEFLAGS) $(TEST_SUITE_LOG) TEST_LOGS="$$log_list"; \
	exit $$?;
recheck: all $(check_PROGRAMS)
	@test -z "$(TEST_SUITE_LOG)" || rm -f $(TEST_SUITE_LOG)
	@set +e; $(am__set_TESTS_bases); \
	bases=`for i in $$bases; do echo $$i; done \
	         | $(am__list_recheck_tests)` || exit 1; \
	log_list=`for i in $$bases; do echo $$i.log; done`; \
	log_list=`echo $$log_list`; \
	$(MAKE) $(AM_MAKEFLAGS) $(TEST_SUITE_LOG) \
	        am__force_recheck=am--force-recheck \
	        TEST_LOGS="$$log_list"; \
	exit $$?
script/basic/tst/basic_ops1.sh.log: script/basic/tst/basic_ops1.sh
	@p='script/basic/tst/basic_ops1.sh'; \
	b='script/basic/tst/basic_ops1.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops2.sh.log: script/basic/tst/basic_ops2.sh
	@p='script/basic/tst/basic_ops2.sh'; \
	b='script/basic/tst/basic_ops2.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops3.sh.log: script/basic/tst/basic_ops3.sh
	@p='script/basic/tst/basic_ops3.sh'; \
	b='script/basic/tst/basic_ops3.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops4.sh.log: script/basic/tst/basic_ops4.sh
	@p='script/basic/tst/basic_ops4.sh'; \
	b='script/basic/tst/basic_ops4.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops5.sh.log: script/basic/tst/basic_ops5.sh
	@p='script/basic/tst/basic_ops5.sh'; \
	b='script/basic/tst/basic_ops5.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops6.sh.log: script/basic/tst/basic_ops6.sh
	@p='script/basic/tst/basic_ops6.sh'; \
	b='script/basic/tst/basic_ops6.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops7.sh.log: script/basic/tst/basic_ops7.sh
	@p='script/basic/tst/basic_ops7.sh'; \
	b='script/basic/tst/basic_ops7.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops8.sh.log: script/basic/tst/basic_ops8.sh
	@p='script/basic/tst/basic_ops8.sh'; \
	b='script/basic/tst/basic_ops8.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops9.sh.log: script/basic/tst/basic_ops9.sh
	@p='script/basic/tst/basic_ops9.sh'; \
	b='script/basic/tst/basic_ops9.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops10.sh.log: script/basic/tst/basic_ops10.sh
	@p='script/basic/tst/basic_ops10.sh'; \
	b='script/basic/tst/basic_ops10.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops11.sh.log: script/basic/tst/basic_ops11.sh
	@p='script/basic/tst/basic_ops11.sh'; \
	b='script/basic/tst/basic_ops11.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops12.sh.log: script/basic/tst/basic_ops12.sh
	@p='script/basic/tst/basic_ops12.sh'; \
	b='script/basic/tst/basic_ops12.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
script/basic/tst/basic_ops13.sh.log: script/basic/tst/basic_ops13.sh
	@p='script/basic/tst/basic_ops13.sh'; \
	b='script/basic/tst/basic_ops13.sh'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
t_monomials.log: t_monomials$(EXEEXT)
	@p='t_monomials$(EXEEXT)'; \
	b='t_monomials'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
t_monomial_pow.log: t_monomial_pow$(EXEEXT)
	@p='t_monomial_pow$(EXEEXT)'; \
	b='t_monomial_pow'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
t_grades.log: t_grades$(EXEEXT)
	@p='t_grades$(EXEEXT)'; \
	b='t_grades'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
t_polynomials.log: t_polynomials$(EXEEXT)
	@p='t_polynomials$(EXEEXT)'; \
	b='t_polynomials'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
t_polynomial_derive.log: t_polynomial_derive$(EXEEXT)
	@p='t_polynomial_derive$(EXEEXT)'; \
	b='t_polynomial_derive'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
t_polynomial_eval.log: t_polynomial_eval$(EXEEXT)
	@p='t_polynomial_eval$(EXEEXT)'; \
	b='t_polynomial_eval'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
t_polynomial_div.log: t_polynomial_div$(EXEEXT)
	@p='t_polynomial_div$(EXEEXT)'; \
	b='t_polynomial_div'; \
	$(am__check_pre) $(LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_LOG_DRIVER_FLAGS) $(LOG_DRIVER_FLAGS) -- $(LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
.test.log:
	@p='$<'; \
	$(am__set_b); \
	$(am__check_pre) $(TEST_LOG_DRIVER) --test-name "$$f" \
	--log-file $$b.log --trs-file $$b.trs \
	$(am__common_driver_flags) $(AM_TEST_LOG_DRIVER_FLAGS) $(TEST_LOG_DRIVER_FLAGS) -- $(TEST_LOG_COMPILE) \
	"$$tst" $(AM_TESTS_FD_REDIRECT)
#.test$(EXEEXT).log:
#	@p='$<'; \
#	$(am__set_b); \
#	$(am__check_pre) $(TEST_LOG_DRIVER) --test-name "$$f" \
#	--log-file $$b.log --trs-file $$b.trs \
#	$(am__common_driver_flags) $(AM_TEST_LOG_DRIVER_FLAGS) $(TEST_LOG_DRIVER_FLAGS) -- $(TEST_LOG_COMPILE) \
#	"$$tst" $(AM_TESTS_FD_REDIRECT)

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(LTLIBRARIES) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:
	-test -z "$(TEST_LOGS)" || rm -f $(TEST_LOGS)
	-test -z "$(TEST_LOGS:.log=.trs)" || rm -f $(TEST_LOGS:.log=.trs)
	-test -z "$(TEST_SUITE_LOG)" || rm -f $(TEST_SUITE_LOG)

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f script/basic/$(DEPDIR)/$(am__dirstamp)
	-rm -f script/basic/$(am__dirstamp)
	-rm -f script/polynomials/$(DEPDIR)/$(am__dirstamp)
	-rm -f script/polynomials/$(am__dirstamp)
	-rm -f src/num_q/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/num_q/$(am__dirstamp)
	-rm -f src/num_z/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/num_z/$(am__dirstamp)
	-rm -f src/num_zm/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/num_zm/$(am__dirstamp)
	-rm -f src/polynomial/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/polynomial/$(am__dirstamp)
	-rm -f src/symbolic/Expr/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/symbolic/Expr/$(am__dirstamp)
	-rm -f src/symbolic/functions/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/symbolic/functions/$(am__dirstamp)
	-rm -f src/symbolic/term/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/symbolic/term/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-checkPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf script/basic/$(DEPDIR) script/polynomials/$(DEPDIR) src/num_q/$(DEPDIR) src/num_z/$(DEPDIR) src/num_zm/$(DEPDIR) src/polynomial/$(DEPDIR) src/symbolic/Expr/$(DEPDIR) src/symbolic/functions/$(DEPDIR) src/symbolic/term/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-includeHEADERS

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf script/basic/$(DEPDIR) script/polynomials/$(DEPDIR) src/num_q/$(DEPDIR) src/num_z/$(DEPDIR) src/num_zm/$(DEPDIR) src/polynomial/$(DEPDIR) src/symbolic/Expr/$(DEPDIR) src/symbolic/functions/$(DEPDIR) src/symbolic/term/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-includeHEADERS uninstall-libLTLIBRARIES

.MAKE: all check-am install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-TESTS \
	check-am clean clean-checkPROGRAMS clean-cscope clean-generic \
	clean-libLTLIBRARIES clean-libtool cscope cscopelist-am ctags \
	ctags-am dist dist-all dist-bzip2 dist-gzip dist-lzip \
	dist-shar dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-includeHEADERS install-info \
	install-info-am install-libLTLIBRARIES install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	recheck tags tags-am uninstall uninstall-am \
	uninstall-includeHEADERS uninstall-libLTLIBRARIES

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
